import {timestamp} from "../../../../../../../../../../../timestamp/module.ts";
import {timeRange} from "../../../../../../../../../time-range/module.ts";
import {time} from "../../../../../../../../../time/module.ts";
import {z} from "zod";
export const schema = z.strictObject({
	"AcceptanceStatus": z.literal(0),
	"ArchivalPortal": z.literal(false),
	"AttachmentsExist": z.boolean(),
	"Cancelled": z.boolean(),
	"CargoAmount": z.union([z.literal(``), z.literal(`20.000`)]),
	"Carrier": z.union([z.string().nonempty(), z.literal(null)]),
	"CarrierAcceptation": z.literal(null),
	"CarrierAcceptationDate": z.literal(null),
	"CarrierAcceptationUser": z.literal(null),
	"CarrierAcceptationUserId": z.literal(null),
	"CarrierCharges": z.union([z.literal(0), z.int().positive()]),
	"CarrierChargesCurrency": z.union([z.string().nonempty(), z.literal(null)]),
	"CarrierChargesWitoutDiscount": z.union([z.literal(0), z.int().positive()]),
	"CarrierChargesWitoutDiscountCurrency": z.union([
		z.string().nonempty(),
		z.literal(null),
	]),
	"CarrierDaysOfDefermentOfPayment": z.union([
		z.literal(0),
		z.int().positive(),
	]),
	"CarrierFAAccount": z.union([z.literal(null), z.literal(``)]),
	"CarrierFullName": z.union([z.string().nonempty(), z.literal(null)]),
	"CarrierId": z.union([z.int().positive(), z.literal(null)]),
	"CarrierReferenceNumber": z.literal(``),
	"CarrierRefNo": z.literal(``),
	"CommentsForCarrier": z.literal(``),
	"CommentsFromCarrier": z.literal(null),
	"CompanyId": z.union([z.int().positive(), z.literal(null)]),
	"CostInvoiceNumber": z.union([z.literal(``), z.string().nonempty()]),
	"CostInvoiceStatus": z.union([z.literal(``), z.literal(`Spłacona`)]),
	"Customer": z.union([z.string().nonempty(), z.literal(``)]),
	"CustomerLoadedKm": z.union([z.int().positive(), z.literal(0)]),
	"Description": z.literal(``),
	"Discount": z.literal(0),
	"Driver1": z.union([z.string().nonempty(), z.literal(``)]),
	"Driver1BusinessPhone": z.union([z.literal(``), z.string().nonempty()]),
	"Driver1Id": z.union([z.int().positive(), z.literal(0)]),
	"Driver1IdentityCard": z.union([
		z.literal(` `),
		z.literal(``),
		z.templateLiteral([z.literal(` `), z.string().nonempty()]),
	]),
	"Driver2": z.literal(``),
	"Driver2BusinessPhone": z.literal(null),
	"Driver2Id": z.union([z.int().positive(), z.literal(0)]),
	"Driver2IdentityCard": z.literal(` `),
	"EInvoiceAcceptance": z.literal(false),
	"ExternalNumber": z.literal(``),
	"FinishDate": z.union([z.literal(null), timestamp.schema.schema]),
	"FinishDateOrder": z.union([z.literal(null), z.int().nonnegative()]),
	"FinishDateRange": z.union([
		z.literal(null),
		z.literal(``),
		timestamp.schema.schema,
		timestamp.schema.schema,
	]),
	"FinishRealDate": z.union([z.literal(null), timestamp.schema.schema]),
	"GMP": z.literal(false),
	/**
	 * Id transportu
	 */
	"Id": z.int().positive(),
	"IdKind": z.int().positive(),
	"ImportOrigin": z.literal(0),
	"InvoicedCosts": z.boolean(),
	"InvoiceState": z.union([z.literal(``), z.literal(`Spłacona`)]),
	"KmTotal": z.union([z.literal(0), z.int().positive()]),
	"KmWithCargo": z.union([z.literal(0), z.int().positive()]),
	"KmWithoutCargo": z.literal(0),
	"LoadingTime": z.union([
		z.literal(``),
		time.schema.schema,
		timeRange.schema.schema,
	]),
	"LTL": z.literal(false),
	"ModificationDate": z.union([z.literal(null), timestamp.schema.schema]),
	"Number": z.union([z.string().nonempty(), z.literal(``)]),
	"NumericalNumber": z.union([z.int().positive(), z.literal(0)]),
	"NumericalTransportNumber": z.union([z.int().positive(), z.literal(0)]),
	"Package": z.union([z.literal(``), z.literal(`paleta`)]),
	"PortalAccess": z.literal(false),
	"PortalAttachmentsExist": z.literal(false),
	"Requirements": z.union([z.literal(``), z.string().nonempty()]),
	"Route": z.union([z.string().nonempty(), z.literal(``)]),
	"SemiTrailer": z.union([z.string().nonempty(), z.literal(``)]),
	"SemiTrailerId": z.union([z.int().positive(), z.literal(0)]),
	"StartDate": z.union([z.literal(null), timestamp.schema.schema]),
	"StartDateOrder": z.union([z.literal(null), z.int().nonnegative()]),
	"StartDateRange": z.union([
		z.null(),
		z.literal(``),
		time.schema.schema,
		timeRange.schema.schema,
	]),
	"StartRealDate": z.union([z.literal(null), timestamp.schema.schema]),
	"State": z.union([z.literal(0), z.literal(1), z.literal(3), z.literal(4)]),
	"StatusKindDescription": z.literal(null),
	"StatusKindId": z.literal(null),
	"TAPA": z.literal(false),
	"Toll": z.literal(0),
	"TollCurrency": z.union([z.string().nonempty(), z.literal(null)]),
	"TollType": z.literal(false),
	"Trailer": z.union([z.string().nonempty(), z.literal(``)]),
	"TrailerId": z.union([z.int().positive(), z.literal(0)]),
	"TransportAuthorId": z.int().positive(),
	"TransportNumber": z.union([z.string().nonempty(), z.literal(``)]),
	"Truck": z.union([z.string().nonempty(), z.literal(``)]),
	"TruckId": z.union([z.int().positive(), z.literal(0)]),
	"UnitAmount": z.union([z.literal(0), z.literal(1)]),
	"UnitAmountType": z.union([z.literal(null), z.literal(`fracht`)]),
	"UnitPrice": z.union([z.literal(0), z.int().positive()]),
	"UnitPriceCurrency": z.union([z.string().nonempty(), z.literal(null)]),
	"UnloadingTime": z.union([
		z.literal(null),
		z.literal(``),
		time.schema.schema,
		timeRange.schema.schema,
	]),
	"WeightInKg": z.union([z.literal(0), z.number().positive()]),
});
