import type {schemaOfBodyOf200ResponseToGetOfMethodsOfDynamicOfRoutesOfTransportOfStaticOfRoutesOfOdataOfStaticOfRoutesOfClient} from "./schema/index.ts";
import type {z} from "zod";
export type BodyOf200ResponseToGetOfMethodsOfDynamicOfRoutesOfTransportOfStaticOfRoutesOfOdataOfStaticOfRoutesOfClient =
	z.output<
		typeof schemaOfBodyOf200ResponseToGetOfMethodsOfDynamicOfRoutesOfTransportOfStaticOfRoutesOfOdataOfStaticOfRoutesOfClient
	>;
