import {timestamp} from "../../../../../../../timestamp/module.ts";
import {z} from "zod";
export const schema = z.strictObject({
	"Carrier": z.string(),
	"CarrierCharge": z.number(),
	"CarrierChargeCurrency": z.string(),
	"CarrierReferenceNumber": z.string(),
	"Driver1": z.strictObject({"FirstName": z.string(), "LastName": z.string()}),
	"Driver2": z.strictObject({"Id": z.number()}),
	"DriverFirstName": z.string(),
	"DriverLastName": z.string(),
	"ExternalNumber": z.string(),
	"IdKind": z.number(),
	"ImportOrigin": z.number(),
	"Shipments": z.array(
		z.strictObject({
			"Customer": z.string(),
			"CustomerReference": z.string(),
			"ExternalNumber": z.string(),
			"Freight": z.number(),
			"FreightCurrency": z.string(),
			"IdKind": z.number(),
			"ImportOrigin": z.number(),
			"Loads": z.array(
				z.strictObject({
					"Adr": z.number(),
					"Height": z.number(),
					"Id": z.number(),
					"Lenght": z.number(),
					"LoadingMeters": z.number(),
					"Name": z.string(),
					"Package": z.string(),
					"Quantity": z.number(),
					"TemperatureMax": z.number(),
					"TemperatureMin": z.number(),
					"TemperatureRequired": z.boolean(),
					"Volume": z.number(),
					"Weight": z.number(),
					"WeightGross": z.number(),
					"WeightGrossKg": z.number(),
					"Width": z.number(),
				}),
			),
			"LoadStationConnections": z.array(
				z.strictObject({
					"Date": timestamp.schema.schema,
					"DateEnd": timestamp.schema.schema,
					"Id": z.number(),
					"IdLoad": z.number(),
					"IdStation": z.number(),
					"LoadingMeters": z.number(),
					"Notes": z.string(),
					"Number": z.string(),
					"Quantity": z.number(),
					"Type": z.number(),
					"Volume": z.number(),
					"Weight": z.number(),
					"WeightGross": z.number(),
				}),
			),
			"Stations": z.array(
				z.strictObject({
					"ApartmentNumber": z.string(),
					"BuildingNumber": z.string(),
					"City": z.string(),
					"Country": z.string(),
					"CountrySymbol": z.string(),
					"Id": z.number(),
					"Name": z.string(),
					"PostalCode": z.string(),
					"Street": z.string(),
				}),
			),
		}),
	),
	"Trailer": z.string(),
	"Truck": z.string(),
	"TruckDescription": z.string(),
	"TruckNotes": z.string(),
});
