import {timestamp} from "../../../../../../../../../../../../timestamp/module.ts";
import {time} from "../../../../../../../../../../time/module.ts";
import {id} from "../../id/module.ts";
import {amountOfKilometers} from "../amount-of-kilometers/module.ts";
import {carrier} from "../Carrier/module.ts";
import {carrierFullName} from "../carrierFullName/module.ts";
import {currency} from "../currency/module.ts";
import {customer} from "../Customer/module.ts";
import {driver} from "../driver/module.ts";
import {identityCard} from "../identity-card/module.ts";
import {number} from "../Number/module.ts";
import {numberOfPhone} from "../number-of-phone/module.ts";
import {numericalNumber} from "../NumericalNumber/module.ts";
import {numericalTransportNumber} from "../NumericalTransportNumber/module.ts";
import {order} from "../order/module.ts";
import {registrationPlate} from "../registration-plate/module.ts";
import {route} from "../Route/module.ts";
import {transportNumber} from "../TransportNumber/module.ts";
import {unitAmountType} from "../UnitAmountType/module.ts";
import {amountOfKilograms} from "../amount-of-kilograms/module.ts";
import {z} from "zod";
export const schema = z.intersection(
	z.strictObject({
		"AcceptanceStatus": z.literal(0),
		"Cancelled": z.literal(false),
		"CargoAmount": z.literal(``),
		"Carrier": carrier.schema,
		"CarrierCharges": z.literal(0),
		"CarrierChargesWitoutDiscount": z.literal(0),
		"CarrierDaysOfDefermentOfPayment": z.literal(0),
		"CarrierFAAccount": z.literal(``),
		"CarrierFullName": carrierFullName.schema,
		"CarrierId": id.schema.schema,
		"CarrierReferenceNumber": z.literal(``),
		"CarrierRefNo": z.literal(``),
		"CommentsForCarrier": z.literal(``),
		"CompanyId": id.schema.schema,
		"CostInvoiceNumber": z.literal(``),
		"CostInvoiceStatus": z.literal(``),
		"Customer": customer.schema,
		"CustomerLoadedKm": amountOfKilometers.schema,
		"Description": z.literal(``),
		"Driver1": driver.schema,
		"Driver1Id": id.schema.schema,
		"Driver2": z.literal(``),
		"Driver2BusinessPhone": z.literal(null),
		"Driver2Id": z.literal(0),
		"EInvoiceAcceptance": z.literal(false),
		"ExternalNumber": z.literal(``),
		"FinishDate": timestamp.schema.schema,
		"FinishDateOrder": order.schema,
		"FinishDateRange": time.schema.schema,
		"GMP": z.literal(false),
		"ImportOrigin": z.literal(0),
		"InvoicedCosts": z.literal(false),
		"InvoiceState": z.literal(``),
		"LoadingTime": time.schema.schema,
		"LTL": z.literal(false),
		"ModificationDate": timestamp.schema.schema,
		"Number": number.schema,
		"NumericalNumber": numericalNumber.schema,
		"NumericalTransportNumber": numericalTransportNumber.schema,
		"Package": z.literal(``),
		"Requirements": z.literal(``),
		"Route": route.schema,
		"StartDate": timestamp.schema.schema,
		"StartDateOrder": order.schema,
		"StartDateRange": time.schema.schema,
		"State": z.literal(5),
		"StatusKindDescription": z.literal(null),
		"StatusKindId": z.literal(null),
		"TAPA": z.literal(false),
		"TollCurrency": currency.schema,
		"TransportAuthorId": id.schema.schema,
		"TransportNumber": transportNumber.schema,
		"Truck": registrationPlate.schema,
		"TruckId": id.schema.schema,
		"UnitAmount": z.literal(1),
		"UnitAmountType": unitAmountType.schema,
		"UnitPrice": z.literal(0),
		"UnloadingTime": time.schema.schema,
	}),
	z.union([
		z.strictObject({
			"AttachmentsExist": z.literal(true),
			"CarrierChargesCurrency": currency.schema,
			"CarrierChargesWitoutDiscountCurrency": currency.schema,
			"Driver1BusinessPhone": numberOfPhone.schema,
			"Driver1IdentityCard": z.literal(` `),
			"FinishRealDate": timestamp.schema,
			"KmTotal": amountOfKilometers.schema,
			"KmWithCargo": amountOfKilometers.schema,
			"KmWithoutCargo": amountOfKilometers.schema,
			"SemiTrailer": registrationPlate.schema,
			"SemiTrailerId": id.schema,
			"StartRealDate": z.literal(null),
			"Trailer": registrationPlate.schema,
			"TrailerId": id.schema,
			"UnitPriceCurrency": currency.schema,
			"WeightInKg": amountOfKilograms.schema,
		}),
		z.strictObject({
			"AttachmentsExist": z.literal(true),
			"CarrierChargesCurrency": currency.schema,
			"CarrierChargesWitoutDiscountCurrency": currency.schema,
			"Driver1BusinessPhone": z.literal(``),
			"Driver1IdentityCard": z.literal(` `),
			"FinishRealDate": timestamp.schema,
			"KmTotal": amountOfKilometers.schema,
			"KmWithCargo": amountOfKilometers.schema,
			"KmWithoutCargo": amountOfKilometers.schema,
			"SemiTrailer": registrationPlate.schema,
			"SemiTrailerId": id.schema,
			"StartRealDate": timestamp.schema,
			"Trailer": registrationPlate.schema,
			"TrailerId": id.schema,
			"UnitPriceCurrency": currency.schema,
			"WeightInKg": amountOfKilograms.schema,
		}),
		z.strictObject({
			"AttachmentsExist": z.literal(true),
			"CarrierChargesCurrency": currency.schema,
			"CarrierChargesWitoutDiscountCurrency": currency.schema,
			"Driver1BusinessPhone": z.literal(``),
			"Driver1IdentityCard": z.literal(` `),
			"FinishRealDate": timestamp.schema,
			"KmTotal": z.literal(0),
			"KmWithCargo": z.literal(0),
			"KmWithoutCargo": z.literal(0),
			"SemiTrailer": z.literal(``),
			"SemiTrailerId": z.literal(0),
			"StartRealDate": timestamp.schema,
			"Trailer": z.literal(``),
			"TrailerId": z.literal(0),
			"UnitPriceCurrency": currency.schema,
			"WeightInKg": z.literal(0),
		}),
		z.strictObject({
			"AttachmentsExist": z.literal(true),
			"CarrierChargesCurrency": currency.schema,
			"CarrierChargesWitoutDiscountCurrency": currency.schema,
			"Driver1BusinessPhone": z.literal(``),
			"Driver1IdentityCard": identityCard.schema,
			"FinishRealDate": timestamp.schema,
			"KmTotal": z.literal(0),
			"KmWithCargo": z.literal(0),
			"KmWithoutCargo": z.literal(0),
			"SemiTrailer": z.literal(``),
			"SemiTrailerId": z.literal(0),
			"StartRealDate": timestamp.schema,
			"Trailer": z.literal(``),
			"TrailerId": z.literal(0),
			"UnitPriceCurrency": currency.schema,
			"WeightInKg": z.literal(0),
		}),
		z.strictObject({
			"AttachmentsExist": z.literal(true),
			"CarrierChargesCurrency": currency.schema,
			"CarrierChargesWitoutDiscountCurrency": currency.schema,
			"Driver1BusinessPhone": z.literal(``),
			"Driver1IdentityCard": z.literal(` `),
			"FinishRealDate": timestamp.schema,
			"KmTotal": z.literal(0),
			"KmWithCargo": z.literal(0),
			"KmWithoutCargo": z.literal(0),
			"SemiTrailer": registrationPlate.schema,
			"SemiTrailerId": id.schema,
			"StartRealDate": timestamp.schema,
			"Trailer": registrationPlate.schema,
			"TrailerId": id.schema,
			"UnitPriceCurrency": currency.schema,
			"WeightInKg": z.literal(0),
		}),
		z.strictObject({
			"AttachmentsExist": z.literal(true),
			"CarrierChargesCurrency": currency.schema,
			"CarrierChargesWitoutDiscountCurrency": currency.schema,
			"Driver1BusinessPhone": z.literal(``),
			"Driver1IdentityCard": z.literal(` `),
			"FinishRealDate": timestamp.schema,
			"KmTotal": z.literal(0),
			"KmWithCargo": z.literal(0),
			"KmWithoutCargo": z.literal(0),
			"SemiTrailer": registrationPlate.schema,
			"SemiTrailerId": id.schema,
			"StartRealDate": timestamp.schema,
			"Trailer": registrationPlate.schema,
			"TrailerId": id.schema,
			"UnitPriceCurrency": currency.schema,
			"WeightInKg": amountOfKilograms.schema,
		}),
		z.strictObject({
			"AttachmentsExist": z.literal(true),
			"CarrierChargesCurrency": currency.schema,
			"CarrierChargesWitoutDiscountCurrency": currency.schema,
			"Driver1BusinessPhone": z.literal(``),
			"Driver1IdentityCard": z.literal(` `),
			"FinishRealDate": z.literal(null),
			"KmTotal": z.literal(0),
			"KmWithCargo": z.literal(0),
			"KmWithoutCargo": z.literal(0),
			"SemiTrailer": z.literal(``),
			"SemiTrailerId": z.literal(0),
			"StartRealDate": z.literal(null),
			"Trailer": z.literal(``),
			"TrailerId": z.literal(0),
			"UnitPriceCurrency": currency.schema,
			"WeightInKg": z.literal(0),
		}),
		z.strictObject({
			"AttachmentsExist": z.literal(false),
			"CarrierChargesCurrency": z.literal(null),
			"CarrierChargesWitoutDiscountCurrency": z.literal(null),
			"Driver1BusinessPhone": z.literal(``),
			"Driver1IdentityCard": z.literal(` `),
			"FinishRealDate": timestamp.schema,
			"KmTotal": z.literal(0),
			"KmWithCargo": z.literal(0),
			"KmWithoutCargo": z.literal(0),
			"SemiTrailer": registrationPlate.schema,
			"SemiTrailerId": id.schema,
			"StartRealDate": timestamp.schema,
			"Trailer": registrationPlate.schema,
			"TrailerId": id.schema,
			"UnitPriceCurrency": z.literal(null),
			"WeightInKg": z.literal(0),
		}),
	]),
);
